# Not a program:-
#
# ELEMENT WISE MULTIPLICATION :-
# 1. TENSORS SHOULD HAVE THE SAME SHAPE, OR THEY SHOULD BE BROADCASTABLE ATLEAST
#
# MATRIX MULTIPLICATION :-
# 1. KNOWN AS "DOT PRODUCT".
# 2. THE INNER DIMENSIONS OF BOTH TENSORS SHOULD MATCH.
# 3. COMBINES ROWS FROM THE FIRST TENSOR WITH THE COLUMNS FROM THE SECOND TENSOR.
