import torch

# DIMENSION PERMUTATION : GOES BEYOND TRANSPOSE AND GIVES PRECISE CONTROLS TO RE-ORDER.
# WE CAN CONVERT shape(0,1,2) TO shape(1,2,0) etc.

# USE CASE EXAMPLE :-
# IN COMPUTER VISION, IMAGE LIBRARIES UPLOAD IMAGES AS (HEIGHT, WIDTH, CHANNELS) OR HWC.
# PYTORCH MODELS EXPECT (CHANNELS, HEIGHT, WIDTH) OR CHW.
# SO PERFORMING PERMUTATION IS IMPORTANT IN SPECIFIC CASES, NOT JUST TRANSPOSE.

a = torch.rand(64, 64, 3)  # THE SHAPE
print(a.shape)

b = a.permute(2, 0, 1)  # THE DIMENSION ORDER (0,1,2) ORDERED INTO (2,0,1)
print(b.shape)
